defaults:
  - _self_

hydra:
  run:
    dir: ../output/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: False
  job_logging:
    formatters:
      simple:
        format: "%(asctime)s [%(levelname)s][%(module)s] %(message)s"

wandb:
  enabled: True
  entity: imokuri
  project: msci  # Multimodal Single-Cell Integration
  dir: ../cache
  group: ${global_params.method}

settings:
  print_freq: 100
  # gpus: "0,1"

  dirs:
    working: ..
    input: ${settings.dirs.working}/input
    output: ${settings.dirs.working}/output
    feature: ${settings.dirs.working}/feature
    preprocess: ${settings.dirs.working}/preprocess
    postprocess: ${settings.dirs.working}/postprocess
    # train_image: ${settings.dirs.input}/train/
    # test_image: ${settings.dirs.input}/test/
    # other_image: ${settings.dirs.input}/other/

  inputs:
    - evaluation_ids.csv
    - metadata.csv
    - sample_submission.csv

    - test_cite_inputs.h5
    - test_cite_inputs_day_2_donor_27678.h5
    - train_cite_inputs.h5
    - train_cite_targets.h5

    # - test_multi_inputs.h5
    # - train_multi_inputs.h5
    - train_multi_targets.h5

    - train_multi_GL_inputs__100.pickle
    - train_multi_KI_inputs__100.pickle
    - train_multi_chr10_inputs_pca_100.pickle
    - train_multi_chr11_inputs_pca_100.pickle
    - train_multi_chr12_inputs_pca_100.pickle
    - train_multi_chr13_inputs_pca_100.pickle
    - train_multi_chr14_inputs_pca_100.pickle
    - train_multi_chr15_inputs_pca_100.pickle
    - train_multi_chr16_inputs_pca_100.pickle
    - train_multi_chr17_inputs_pca_100.pickle
    - train_multi_chr18_inputs_pca_100.pickle
    - train_multi_chr19_inputs_pca_100.pickle
    - train_multi_chr1_inputs_pca_400.pickle
    - train_multi_chr20_inputs_pca_100.pickle
    - train_multi_chr21_inputs_pca_100.pickle
    - train_multi_chr22_inputs_pca_100.pickle
    - train_multi_chr2_inputs_pca_200.pickle
    - train_multi_chr3_inputs_pca_100.pickle
    - train_multi_chr4_inputs_pca_100.pickle
    - train_multi_chr5_inputs_pca_100.pickle
    - train_multi_chr6_inputs_pca_100.pickle
    - train_multi_chr7_inputs_pca_100.pickle
    - train_multi_chr8_inputs_pca_100.pickle
    - train_multi_chr9_inputs_pca_100.pickle
    - train_multi_chrX_inputs_pca_100.pickle
    - train_multi_chrY_inputs_pca_100.pickle

    - test_multi_GL_inputs__100.pickle
    - test_multi_KI_inputs__100.pickle
    - test_multi_chr10_inputs_pca_100.pickle
    - test_multi_chr11_inputs_pca_100.pickle
    - test_multi_chr12_inputs_pca_100.pickle
    - test_multi_chr13_inputs_pca_100.pickle
    - test_multi_chr14_inputs_pca_100.pickle
    - test_multi_chr15_inputs_pca_100.pickle
    - test_multi_chr16_inputs_pca_100.pickle
    - test_multi_chr17_inputs_pca_100.pickle
    - test_multi_chr18_inputs_pca_100.pickle
    - test_multi_chr19_inputs_pca_100.pickle
    - test_multi_chr1_inputs_pca_400.pickle
    - test_multi_chr20_inputs_pca_100.pickle
    - test_multi_chr21_inputs_pca_100.pickle
    - test_multi_chr22_inputs_pca_100.pickle
    - test_multi_chr2_inputs_pca_200.pickle
    - test_multi_chr3_inputs_pca_100.pickle
    - test_multi_chr4_inputs_pca_100.pickle
    - test_multi_chr5_inputs_pca_100.pickle
    - test_multi_chr6_inputs_pca_100.pickle
    - test_multi_chr7_inputs_pca_100.pickle
    - test_multi_chr8_inputs_pca_100.pickle
    - test_multi_chr9_inputs_pca_100.pickle
    - test_multi_chrX_inputs_pca_100.pickle
    - test_multi_chrY_inputs_pca_100.pickle

    # - train.csv
    # - test.csv
    # - sample_submission.csv

  preprocesses:
    # - train_cite_inputs.pickle
    - train_cite_all_inputs_ivis_240.pickle
    - train_cite_all_inputs_pca_240.pickle
    - train_cite_no_pca_inputs.pickle
    # - train_cite_sum_by_rna_type_inputs.pickle
    # - train_cite_mean_by_rna_type_inputs.pickle
    # - train_cite_std_by_rna_type_inputs.pickle
    # - train_cite_skew_by_rna_type_inputs.pickle

    - train_cite_targets.pickle

    # - test_cite_inputs.pickle
    - test_cite_all_inputs_ivis_240.pickle
    - test_cite_all_inputs_pca_240.pickle
    - test_cite_no_pca_inputs.pickle
    # - test_cite_sum_by_rna_type_inputs.pickle
    # - test_cite_mean_by_rna_type_inputs.pickle
    # - test_cite_std_by_rna_type_inputs.pickle
    # - test_cite_skew_by_rna_type_inputs.pickle

    - train_multi_GL_inputs__100.pickle
    - train_multi_KI_inputs__100.pickle
    - train_multi_chr10_inputs_pca_100.pickle
    - train_multi_chr11_inputs_pca_100.pickle
    - train_multi_chr12_inputs_pca_100.pickle
    - train_multi_chr13_inputs_pca_100.pickle
    - train_multi_chr14_inputs_pca_100.pickle
    - train_multi_chr15_inputs_pca_100.pickle
    - train_multi_chr16_inputs_pca_100.pickle
    - train_multi_chr17_inputs_pca_100.pickle
    - train_multi_chr18_inputs_pca_100.pickle
    - train_multi_chr19_inputs_pca_100.pickle
    - train_multi_chr1_inputs_pca_400.pickle
    - train_multi_chr20_inputs_pca_100.pickle
    - train_multi_chr21_inputs_pca_100.pickle
    - train_multi_chr22_inputs_pca_100.pickle
    - train_multi_chr2_inputs_pca_200.pickle
    - train_multi_chr3_inputs_pca_100.pickle
    - train_multi_chr4_inputs_pca_100.pickle
    - train_multi_chr5_inputs_pca_100.pickle
    - train_multi_chr6_inputs_pca_100.pickle
    - train_multi_chr7_inputs_pca_100.pickle
    - train_multi_chr8_inputs_pca_100.pickle
    - train_multi_chr9_inputs_pca_100.pickle
    - train_multi_chrX_inputs_pca_100.pickle
    - train_multi_chrY_inputs_pca_100.pickle
    - train_multi_all_inputs_ivis_240.pickle

    - train_multi_targets.pickle

    - test_multi_GL_inputs__100.pickle
    - test_multi_KI_inputs__100.pickle
    - test_multi_chr10_inputs_pca_100.pickle
    - test_multi_chr11_inputs_pca_100.pickle
    - test_multi_chr12_inputs_pca_100.pickle
    - test_multi_chr13_inputs_pca_100.pickle
    - test_multi_chr14_inputs_pca_100.pickle
    - test_multi_chr15_inputs_pca_100.pickle
    - test_multi_chr16_inputs_pca_100.pickle
    - test_multi_chr17_inputs_pca_100.pickle
    - test_multi_chr18_inputs_pca_100.pickle
    - test_multi_chr19_inputs_pca_100.pickle
    - test_multi_chr1_inputs_pca_400.pickle
    - test_multi_chr20_inputs_pca_100.pickle
    - test_multi_chr21_inputs_pca_100.pickle
    - test_multi_chr22_inputs_pca_100.pickle
    - test_multi_chr2_inputs_pca_200.pickle
    - test_multi_chr3_inputs_pca_100.pickle
    - test_multi_chr4_inputs_pca_100.pickle
    - test_multi_chr5_inputs_pca_100.pickle
    - test_multi_chr6_inputs_pca_100.pickle
    - test_multi_chr7_inputs_pca_100.pickle
    - test_multi_chr8_inputs_pca_100.pickle
    - test_multi_chr9_inputs_pca_100.pickle
    - test_multi_chrX_inputs_pca_100.pickle
    - test_multi_chrY_inputs_pca_100.pickle
    - test_multi_all_inputs_ivis_240.pickle

    - metadata.pickle

    - cite_adversarial_oof.pickle
    - multi_adversarial_oof.pickle

  postprocesses:
    - evaluation_ids.csv
    - metadata.csv
    - sample_submission.csv

    # - cite_inference.pickle
    # - cite_oof.pickle
    - cite_adversarial_oof.pickle
    - train_cite_targets.pickle

    # - multi_inference.pickle
    # - multi_oof.pickle
    - multi_adversarial_oof.pickle
    - train_multi_targets.pickle

  debug: False
  n_debug_data: 0

  amp: True
  multi_gpu: True

  skip_training: False
  skip_inference: False  # ** adversarial

  label_name: label
  n_class: 1
  scoring: pearson  # pearson, accuracy  # ** adversarial

# These parameters are main tuning parameters and recorded to wandb.
params:
  seed: ${global_params.seed}
  data: ${global_params.data}

global_params:
  seed: 440
  method: tabnet  # tabnet, adversarial_tabnet  # ** adversarial
  data: cite  # cite, multi

preprocess_params:
  cols: all  # all, chr1 ~ chr22, chrX, chrY, GL, KI
  methods:
    # - pca
    # - ivis
    - ivis_supervised
    # - faiss
  pca_n_components_cite: 240
  pca_n_components_multi: 240
  ivis_n_components_cite: 240
  ivis_n_components_multi: 240
  cite_no_pca_cols:
    # processed_pseudogene
    # ENSG00000255909_PDCD5P1
    # https://asia.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000255909;r=12:19413153-19413461;t=ENST00000543528
    - ENSG00000139154_AEBP2

    # transcribed_unprocessed_pseudogene
    # ENSG00000229391_HLA-DRB6
    - ENSG00000251916_RNU1-61P

    # unprocessed_pseudogene
    # ENSG00000244703_CD46P1
    - ENSG00000197721_CR1L

    # antisense_RNA
    # ENSG00000238184_CD81-AS1
    - ENSG00000236264_RPL26P30
    - ENSG00000110651_CD81

    # ENSG00000203497_PDCD4-AS1
    - ENSG00000150593_PDCD4

    # ENSG00000255443_CD44-AS1
    - ENSG00000026508_CD44

    # nonsense_mediated_decay
    # ENSG00000071994_PDCD2
    - ENSG00000112592_TBP

    # ENSG00000091972_CD200
    # ENSG00000206531_CD200R1L
    # ENSG00000002586_CD99

    # retained_intron
    # ENSG00000111731_C2CD5
    - ENSG00000256973_AC053513.1

    # ENSG00000103855_CD276
    # ENSG00000204592_HLA-E

    # ENSG00000215039_CD27-AS1
    - ENSG00000139193_CD27
    - ENSG00000139192_TAPBPL

    # ENSG00000010610_CD4
    - ENSG00000089692_LAG3
    - ENSG00000250510_GPR162

    # ENSG00000012124_CD22

    # ENSG00000168014_C2CD3
    - ENSG00000214517_PPME1
    - ENSG00000175564_UCP3

    # ENSG00000135535_CD164
    - ENSG00000260273_AL359711.2

    # ENSG00000182685_BRICD5
    - ENSG00000184207_PGP
    - ENSG00000167965_MLST8

    # ENSG00000085063_CD59

    # ENSG00000172375_C2CD2L
    - ENSG00000188486_H2AFX
    - ENSG00000172269_DPAGT1

    # ENSG00000134061_CD180
    # ENSG00000167286_CD3D

    # ENSG00000223773_CD99P1
    - ENSG00000230542_LINC00102

    # ENSG00000198851_CD3E
    # ENSG00000110848_CD69

    # ENSG00000169217_CD2BP2
    - ENSG00000260219_AC106782.2
    - ENSG00000169221_TBC1D10B

    # ENSG00000177455_CD19
    - ENSG00000177548_RABEP2

    # ENSG00000167851_CD300A

    # ENSG00000186074_CD300LF
    - ENSG00000172794_RAB37

    # ENSG00000075035_WSCD2
    # ENSG00000105185_PDCD5

    # ENSG00000090470_PDCD7
    - ENSG00000246922_UBAP1L

    # ENSG00000007312_CD79B

    # ENSG00000126249_PDCD2L
    - ENSG00000105220_GPI
    - ENSG00000126261_UBA2

    # ENSG00000019582_CD74
    - ENSG00000070814_TCOF1

    # ENSG00000121594_CD80
    - ENSG00000113845_TIMMDC1

    # processed_transcript
    # ENSG00000132300_PTCD3
    - ENSG00000068654_POLR1A
    - ENSG00000132305_IMMT

    # ENSG00000119688_ABCD4
    - ENSG00000258559_AC005519.1

    # ENSG00000120217_CD274

    # ENSG00000102181_CD99L2
    - ENSG00000063601_MTMR1

    - ENSG00000102181_CD99L2

    # ENSG00000122223_CD244
    - ENSG00000122224_LY9

    # ENSG00000169442_CD52
    - ENSG00000158062_UBXN11
    - ENSG00000176092_CRYBG2

    # ENSG00000254126_CD8B2
    # ENSG00000143119_CD53
    # ENSG00000101017_CD40

    # ENSG00000167775_CD320
    - ENSG00000267855_NDUFA7

    # ENSG00000066294_CD84
    - ENSG00000234425_AL138930.1

    # ENSG00000105383_CD33
    # ENSG00000272398_CD24
    # ENSG00000010278_CD9

    # ENSG00000174059_CD34
    - ENSG00000285719_AL356275.2
    - ENSG00000203709_MIR29B2CHG

    # ENSG00000170584_NUDCD2
    - ENSG00000072571_HMMR
    - ENSG00000113328_CCNG1

    # ENSG00000241399_CD302
    - ENSG00000136536_MARCH7
    - ENSG00000054219_LY75

    # ENSG00000144554_FANCD2
    - ENSG00000186162_CIDECP

    # ENSG00000117528_ABCD3

    # ENSG00000134256_CD101
    - ENSG00000236137_AL445231.1

    # ENSG00000049883_PTCD2
    - ENSG00000113048_MRPS27

    # ENSG00000188921_HACD4
    - ENSG00000188352_FOCAD

    # ENSG00000104894_CD37
    - ENSG00000197813_AC011450.1
    - ENSG00000074219_TEAD2

    # ENSG00000198821_CD247
    - ENSG00000143190_POU2F1

    # ENSG00000161714_PLCD3
    - ENSG00000181513_ACBD4
    - ENSG00000136448_NMT1

    # ENSG00000157617_C2CD2
    - ENSG00000141956_PRDM15
    - ENSG00000227698_AP001619.1

    # ENSG00000198087_CD2AP
    - ENSG00000270761_AL355353.1

    # ENSG00000137101_CD72
    - ENSG00000107140_TESK1
    - ENSG00000137078_SIT1

    # ENSG00000196352_CD55

    # ENSG00000074696_HACD3
    - ENSG00000138614_INTS14

    # ENSG00000015676_NUDCD3
    - ENSG00000146677_AC004453.1

    # protein_coding
    # ENSG00000167850_CD300C
    # ENSG00000185963_BICD2
    # ENSG00000004468_CD38

    # ENSG00000108604_SMARCD2
    - ENSG00000087191_PSMC5
    - ENSG00000108592_FTSJ3

    # ENSG00000082014_SMARCD3
    - ENSG00000272661_AC021097.1
    - ENSG00000033100_CHPF2

    # ENSG00000153283_CD96
    - ENSG00000244720_AC055748.1

    # ENSG00000171611_PTCRA
    # ENSG00000196126_HLA-DRB1
    # ENSG00000178789_CD300LB
    # ENSG00000172116_CD8B

    # ENSG00000139187_KLRG1
    - ENSG00000111752_PHC1
    - ENSG00000003056_M6PR

    # ENSG00000117335_CD46
    - ENSG00000234219_CDCA4P4

    # ENSG00000085117_CD82

    # ENSG00000117281_CD160
    - ENSG00000265491_RNF115

    # ENSG00000205502_C2CD4B
    # ENSG00000112149_CD83

    # ENSG00000117091_CD48
    - ENSG00000228863_AL121985.1

    # ENSG00000196776_CD47
    - ENSG00000279277_AC012020.1

    # ENSG00000102245_CD40LG
    - ENSG00000233093_LINC00892
    - ENSG00000129675_ARHGEF6

    # ENSG00000163606_CD200R1
    # ENSG00000125810_CD93

    # ENSG00000116815_CD58
    - ENSG00000177173_NAP1L4P1
    - ENSG00000143061_IGSF3

    # ENSG00000125726_CD70
    # ENSG00000186193_SAPCD2

    # ENSG00000185561_TLCD2
    - ENSG00000186594_MIR22HG

    # ENSG00000173762_CD7
    - ENSG00000141574_SECTM1

    # ENSG00000105369_CD79A
    - ENSG00000076928_ARHGEF1
    - ENSG00000105372_RPS19

    # ENSG00000135404_CD63
    - ENSG00000258056_AC009779.2
    - ENSG00000135437_RDH5

    # ENSG00000117877_CD3EAP
    - ENSG00000012061_ERCC1
    - ENSG00000104881_PPP1R13L

    # ENSG00000186407_CD300E

    # ENSG00000170458_CD14
    - ENSG00000131495_NDUFA2
    - ENSG00000113119_TMCO6

    # ENSG00000135218_CD36
    # ENSG00000145284_SCD5
    # ENSG00000116824_CD2
    # ENSG00000204287_HLA-DRA

    # ENSG00000206527_HACD2
    - ENSG00000239523_MYLK-AS1

    # ENSG00000174807_CD248
    # ENSG00000168329_CX3CR1

    # ENSG00000150637_CD226
    - ENSG00000206052_DOK6

    # ENSG00000115556_PLCD4
    - ENSG00000115568_ZNF142

    # ENSG00000198502_HLA-DRB5
    # ENSG00000114013_CD86

  cite_drop_cols: []
  multi_drop_cols: []

cv_params:
  n_fold: 5
  n_validation: 1
  fold: stratified  # kfold
  # group_name: patient_id
  # time_name: ""

training_params:
  epoch: 10
  es_patience: 0
  batch_size: 24
  gradient_acc_step: 1
  max_grad_norm: 1000
  # feature_set:
  #   - "f000" # f000_open_close
  criterion: CrossEntropyLoss
  optimizer: Adam
  scheduler: CosineAnnealingWarmupRestarts
  lr: 2e-2
  min_lr: 1e-5
  weight_decay: 1e-5  # AdamW: 0.01, others: 0
  # label_smoothing: 1e-6

model_params:
  dataset: base
  augmentation: light
  model: base
  model_input: 512
  model_name: tf_efficientnet_b4_ns
  # dropout: 0.0

inference_params:
  cite_pretrained:
    2022-09-22_00-48-04: 1  # tabnet
    2022-09-22_01-02-14: 1  # ridge
    2022-09-22_01-06-30: 1  # xgboost
  multi_pretrained:
    # 2022-09-20_14-06-40: 1  # ridge
    2022-09-20_14-23-30: 1  # tabnet
  pretrained: []
  # pretrained:
  #   - dir: ""
  #     model: ""
  #     name: ""
